### PR TITLE
Completed four column layout

### PR DESCRIPTION
**Pull request by ameliatalkington**

### CODE REVIEW

**Review by thebearingedge — CHANGES_REQUESTED** [review]
Please include a screenshot.

**Comment by ameliatalkington** [comment]
Screen Shot 2021-01-26 at 10 53 51 AM

**Review by thebearingedge — CHANGES_REQUESTED** [review]
Looking good, but please restructure your HTML into columns. Each column should contain
- a picture of the phone
- an icon
- a heading
- a text blurb

**Comment by ameliatalkington** [comment]
Screen Shot 2021-01-28 at 3 35 55 PM

**Review by thebearingedge — APPROVED** [review]

**Pull request merged**
