### PR TITLE
Completed CSS ecommerce page

### PR DESCRIPTION
**Pull request by ameliatalkington**

### CODE REVIEW

**Review by codingcodymiller — CHANGES_REQUESTED** [review]
Hey Amelia! Please provide an image of your output

**Review by codingcodymiller — CHANGES_REQUESTED** [review]
Hey Amelia! One adjustment in your HTML before I take a look at the CSS. You may need to revise your CSS after the change, make sure you double check your output 👍

**Comment by ameliatalkington** [comment]
Screen Shot 2021-01-28 at 3 59 14 PM

**Comment by ameliatalkington** [comment]
also looks like i have to resolve branch conflicts?? i thought i was done fighting github lol

**Review by thebearingedge — APPROVED** [review]
Nice! To fix your merge conflict do:
- `git check out master`
- `git pull origin master`
- `git checkout css-ecommerce-page`
- `git merge master`
- fix any conflicts in your files (git will tell you which ones)
- save
- commit
- push again

**Pull request merged**
